zend_extension=xdebug 
[xdebug]
xdebug.mode=debug 
xdebug.start_with_request=yes
## Host Settings ohne docker desktop
# xdebug.discover_client_host=1
## Host Settings mit docker desktop
xdebug.client_host=host.docker.internal 
## Port Settings
xdebug.client_port=9003
xdebug.log=/tmp/xdebug.log 